"""The contract an array satisfies, and what an absent entry means."""

from typing import Any, Protocol, runtime_checkable

ABSENCE = ("empty", "unknown")


@runtime_checkable
class Array(Protocol):
    """A labeled N-dimensional array.

    `absence` states what a coordinate the array does not carry means:
    `"empty"` that it contributes nothing, `"unknown"` that it was not
    modelled. Operators and reductions follow from that declaration, so the
    arithmetic is part of the contract rather than an implementation's own:
    a consumer writing `weights * entries` is writing against this.

    `coords` answers the label question per dimension. It holds coordinates
    rather than label arrays, so a dimension spanning millions of positions
    costs nothing to carry; `labels` names the label arrays a caller states
    and reads back, and is never a coordinate.
    """

    dims: tuple[str, ...]
    shape: tuple[int, ...]
    coords: dict[str, Any]
    absence: str
    nnz: int

    def sel(self, indexers: dict[str, Any]) -> "Array": ...
    def sum(self, dim: str | None = None, **policy: Any) -> Any: ...
    def mean(self, dim: str | None = None, **policy: Any) -> Any: ...
    def min(self, dim: str | None = None, **policy: Any) -> Any: ...
    def max(self, dim: str | None = None, **policy: Any) -> Any: ...
    def shift(self, shifts: dict[str, int], mode: str = "drop") -> "Array": ...
    def roll(self, shifts: dict[str, int]) -> "Array": ...
    def rename(self, names: dict[str, str]) -> "Array": ...
    def transpose(self, *dims: str) -> "Array": ...
    def conform(self, dims: list[str], labels: dict[str, Any]) -> "Array": ...
    def to_dense(self, fill: Any = None) -> Any: ...
    def domain(self, dims: tuple[str, ...] | None = None) -> Any: ...
    def coordinates(self, dims: tuple[str, ...] | None = None) -> Any: ...
    def values(self) -> Any: ...
    def restrict(self, domain: Any) -> "Array": ...
    def expand(self, dims: tuple[str, ...], coords: dict[str, Any]) -> "Array": ...
    def group(
        self,
        dims: tuple[str, ...],
        into: str,
        domain: Any = None,
        offset: int = 0,
        out: Any = None,
    ) -> "Array": ...
    def as_empty(self) -> "Array": ...
    def as_unknown(self) -> "Array": ...
    def __add__(self, other: Any) -> "Array": ...
    def __radd__(self, other: Any) -> "Array": ...
    def __sub__(self, other: Any) -> "Array": ...
    def __rsub__(self, other: Any) -> "Array": ...
    def __mul__(self, other: Any) -> "Array": ...
    def __rmul__(self, other: Any) -> "Array": ...
    def __truediv__(self, other: Any) -> "Array": ...
    def __rtruediv__(self, other: Any) -> "Array": ...
    def __pow__(self, other: Any) -> "Array": ...
    def __neg__(self) -> "Array": ...
