services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/nimblend:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspaces/nimblend
    # Uncomment below to expose additional ports for services you might need
    ports:
      - "8888:8888"  # For Jupyter notebook
