custom_groups:
  DeepSeekCoder:
    model: deepseek/deepseek-coder
  Fireworks_llama33:
    model: fireworks_ai/accounts/fireworks/models/llama-v3p3-70b-instruct
    temperature: 0.8
    top_p: 1
  cerebras_llama3.3:
    model: cerebras/meta/llama3-70b-instruct
  claude37:
    model: anthropic/claude-3-7-sonnet-20250219
  fireworkQwen25Coder:
    model: fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b-instruct
  gemini:
    model: gemini/gemini-1.5-pro-latest
    use_prompt_caching: true
  gemini2:
    model: gemini/gemini-2.0-flash-exp
  gpt4o:
    model: openai/gpt-4o-2024-08-06
  haiku3:
    max_tokens: 3000
    model: anthropic/claude-3-haiku-20240307
    temperature: 0.5
    use_prompt_caching: false
  o1-mini:
    model: openai/gpt-4o-mini-2024-07-18
  phi4:
    api_base: https://api.repoai.dev/ollama
    model: ollama/vanilj/Phi-4
  qwen25coder:
    api_base: https://api.repoai.dev/ollama
    model: ollama/qwen2.5-coder:32b-instruct-q4_0
  sonnet351:
    max_tokens: 8000
    model: anthropic/claude-3-5-sonnet-20240620
    temperature: 0.1
    use_prompt_caching: true
  sonnet352:
    max_tokens: 8000
    model: anthropic/claude-3-5-sonnet-20241022
    temperature: 0.1
    use_prompt_caching: true
workflow_config:
  project_modification_workflow:
    file_edit_task: sonnet351
    project_modification_task: claude37
